#ifndef CUDA_RASTERIZER_CONFIG_H_INCLUDED
#define CUDA_RASTERIZER_CONFIG_H_INCLUDED

#define NUM_CHANNELS 3 // Default 3, RGB
#define BLOCK_X 4
#define BLOCK_Y 4
#define BLOCK_Z 4
#define OPACITY 0.01

#endif